Update aquasec.yml

diff --git a/.github/workflows/aquasec.yml b/.github/workflows/aquasec.yml
--- a/.github/workflows/aquasec.yml
+++ b/.github/workflows/aquasec.yml
@@ -3,17 +3,29 @@ on:
   push:
     branches:
       - master
-  pull_request:
 jobs:
-  build:
-    name: Build
+  repo_scan:
+    name: Repo Scanning
     runs-on: ubuntu-18.04
     steps:
       - name: Checkout code
         uses: actions/checkout@v2
-
-      - name: Run Trivy vulnerability scanner in IaC mode
-        uses: aquasecurity/trivy-action@master
+        
+      # Aqua Registry login
+      - name: Login to Aqua Registry
+        uses: docker/login-action@v1
+        with:
+          registry: registry.aquasec.com
+          username: ${{ secrets.AQUADEV_USERNAME }}
+          password: ${{ secrets.AQUADEV_PASS }}  
+          
+      #- name: Login to DockerHub
+      #  uses: docker/login-action@v2
+      #  with:
+      #    username: ${{ secrets.DOCKERHUB_USERNAME }}
+      #    password: ${{ secrets.DOCKERHUB_TOKEN }}
+      - name: Run Trivy vulnerability scanner - FS mode
+        uses: aquasecurity/trivy-action@0.6.2
         with:
           scan-type: 'fs'
           security-checks: 'vuln,config,secret'
@@ -24,19 +36,35 @@ jobs:
           AQUA_SECRET: ${{ secrets.AQUA_SECRET }}
           TRIVY_RUN_AS_PLUGIN: 'aqua'
           TRIGGERED_BY: 'PUSH'
-            
-      - name: Manifest Generation
-        run: |
-         curl -L ${{ secrets.BILLY_URL }}/v1/api/download/sh | sh
-         billy generate \
-            --access-token "${{ secrets.GITHUB_TOKEN }}" \
-            --aqua-key "${{ secrets.AQUA_KEY }}" \
-            --aqua-secret "${{ secrets.AQUA_SECRET }}" \
-
-            # The docker image name:tag of the newly built imagee
-            --artifact-path "my-image-name:${{ env.tag-version }}" \
-
-            # OR the path to the root folder of your project. I.e my-repo/my-app 
-            --artifact-path "${{env.MY_APP_ROOT}}"
+          GITHUB_TOKEN: ${{ github.token }}
+        
+      # Runs docker build 
+      - name: Build docker image
+        run: docker build -t test:v1 .
           
-   
+      # Scan the test Image
+      - name: Image Scanning
+        run: |
+          docker run  -e BUILD_JOB_NAME=FRUIT_BANK -e BUILD_NUMBER=${{ github.run_id }} -v /var/run/docker.sock:/var/run/docker.sock registry.aquasec.com/scanner:2022.4.46 scan --register --registry "CI/CD_andres_images" --local $CI_REGISTRY_IMAGE:$IMAGE_TAG --host $AQUA_HOST --token $AQUA_SCANNER_TOKEN --show-negligible --html > aquascan.html
+    #Debug: -e SCALOCK_LOG_LEVEL=DEBUG
+        
+      - name: SBOM Manifest Generation
+        run: |
+          curl -sLo install.sh download.codesec.aquasec.com/billy/install.sh
+          curl -sLo install.sh.checksum https://github.com/argonsecurity/releases/releases/latest/download/install.sh.checksum
+          if ! cat install.sh.checksum | shasum -a 256 ; then
+            echo "install.sh checksum failed"
+            exit 1
+          fi
+          sh install.sh
+          rm install.sh install.sh.checksum
+          billy generate \
+              --access-token "${{ secrets.GITHUB_TOKEN }}" \
+              --aqua-key "${{ secrets.AQUA_KEY }}" \
+            --aqua-secret "${{ secrets.AQUA_SECRET }}" \
+            --artifact-path "test:v1" 
+
+        # The docker image name:tag of the newly built image
+        # --artifact-path "my-image-name:${{ env.tag-version }}" 
+        # OR the path to the root folder of your project. I.e my-repo/my-app 
+        # --artifact-path "${{env.MY_APP_ROOT}}"
